Update Ubuntu runners
- Bump Ubuntu 22.04 to 24.04.
- Bump Ubuntu 20.04 to 22.04 because the 20.04 runner image has been
  retired:
  https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

Unfortunately it's not possible to test Python 3.6 any more:
	  Version 3.6 was not found in the local cache
	  Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.